Updated gitlab-ci yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,11 +1,29 @@
+before_script:
+   - |
+   EXPECTED_SIGNATURE=$(wget https://composer.github.io/installer.sig -O - -q)
+   php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+   ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+
+   if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]
+   then
+       php composer-setup.php --quiet
+       RESULT=$?
+       rm composer-setup.php
+       exit $RESULT
+   else
+       >&2 echo 'ERROR: Invalid installer signature'
+       rm composer-setup.php
+       exit 1
+   fi
+   - composer install --dev
 stages:
   - build
   - test
 test:5.6:
   image: php:5.6
   script:
-  - composer exec codecept run
+  - php composer.phar exec codecept run
 test:7.0:
   image: php:7.0
   script:
-  - composer exec codecept run
+  - php composer.phar exec codecept run
